# Generated by Django 4.0.6 on 2022-07-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_cover',
            field=models.CharField(max_length=150),
        ),
    ]
